<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0-windows10.0.22621.0</TargetFramework>
        <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UseWinUI>true</UseWinUI>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <EnableMsixTooling>true</EnableMsixTooling>
        <Platforms>x86;x64;arm64</Platforms>
        <!-- 指定默认运行设置文件，确保测试以 x64 平台运行 -->
        <RunSettingsFilePath>$(MSBuildProjectDirectory)\test.runsettings</RunSettingsFilePath>
        <!-- Disable Windows App SDK auto initialization for tests -->
        <WindowsAppSdkBootstrapInitialize>false</WindowsAppSdkBootstrapInitialize>
        <WindowsAppSdkDeploymentManagerInitialize>false</WindowsAppSdkDeploymentManagerInitialize>
        <WindowsAppSdkAutoInitialize>false</WindowsAppSdkAutoInitialize>
        <WindowsAppSdkUndockedRegFreeWinRTInitialize>false</WindowsAppSdkUndockedRegFreeWinRTInitialize>
        <WindowsAppSdkCompatibilityInitialize>false</WindowsAppSdkCompatibilityInitialize>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
        <PackageReference Include="Moq" Version="4.20.72" />
        <PackageReference Include="NUnit" Version="4.2.2" />
        <PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
        <PackageReference Include="NUnit.Analyzers" Version="4.3.0">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="coverlet.collector" Version="6.0.2">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="SharpCompress" Version="0.48.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\GalgameManager\GalgameManager.csproj" Properties="Platform=x64;PlatformTarget=x64;RuntimeIdentifier=win-x64;WindowsPackageType=None;DefaultLanguage=en-US;EnableMsixTooling=false;GenerateAppxPackageOnBuild=false;PublishReadyToRun=false" />
      <ProjectReference Include="..\GalgameManager.WinApp.Base\GalgameManager.WinApp.Base.csproj" />
    </ItemGroup>


</Project>
