<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.22621.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWinUI>true</UseWinUI>
    <OutputType>Library</OutputType>
    <Platforms>x64</Platforms>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <EnableMsixTooling>false</EnableMsixTooling>
    <AppxGeneratePriEnabled>false</AppxGeneratePriEnabled>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GalgameManager.WinApp.Base\GalgameManager.WinApp.Base.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>
</Project>
